name: "IoT Transparency"
version: 1.0.1

slug: "iot-transparency"
description: "Add-on for Carnegie Mellon University research study"
url: "https://github.com/synergylabs/iot-transparency"
panel_icon: "mdi:lightbulb-question"

image: "ghcr.io/synergylabs/iot-transparency-{arch}"
arch:
  - aarch64
  - amd64
init: false
ingress: true
ingress_port: 8099
host_network: true
privileged:
  - NET_ADMIN
  - NET_RAW
homeassistant: "2025.5"
homeassistant_api: true
options:
  debug_mode: false
  allow_arp_spoofing: true
  erase_database_on_start: false
schema:
  debug_mode: bool
  allow_arp_spoofing: bool
  erase_database_on_start: bool
